[tool.black]
line-length = 115
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \doc\source\conf.py
  | \{{ cookiecutter.repo_nanme }}/setup.py'

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''
