[tool.codespell]
exclude-file = ".codespell/ignore_lines.txt"
ignore-words = ".codespell/ignore_words.txt"
skip = "*.cif,*.dat"

[tool.black]
line-length = 115
include = '\.pyi?$'
exclude = '''
/(
    \.git\
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build/
  | buck-out
  | build
  | dist
  | blib2to3
  | tests/data/
  | hooks/post_gen_project.py$
  | .*\.py$
  | .*\.toml$
)/
'''
