name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  coverage-and-matrix:
    uses: Billingegroup/release-scripts/.github/workflows/_coverage-and-matrix.yml@v0
    with:
      project: PROJECT_NAME
      c_extension: false
      headless: false
